spring:
  datasource:
    bookstore:
      jdbc-url: "jdbc:mysql://localhost:3306/bookstore_ingress"
      username: "root"
      password: "12345"
      type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    change-log: db/changelog/changelog-master.xml
    enabled: true
app:
  jwt:
    secret-key: "VGhpcyBteSBzZWNyZXQga2V5IGZvciBBcHBsaWNhdGlvbi4gUGxlYXNlIGNoYW5nZSBpbiBwcm9kdWN0aW"
#    validity-time: 60000
    validity-time: 300000
